config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # GET all
  get 'tasks', to: 'tasks#index'

  # NEW
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # GET one
  get 'tasks/:id', to: 'tasks#show', as: :task

  # EDIT
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'

  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
<%= task.completed ? "[X]" : "[ ]" %>
    <h4> <%= link_to task.title, task_path(task) %></h4>
    <p><%= link_to "Update this task", edit_path(task) %></p>
    <p><%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
<% end %>
<%= "-------  " %>
<%= link_to "Add new task", tasks_new_path  %>
<%= "  -------" %>

app/views/tasks/new.html.erb
<!-- form_for is a rails helper method to help you generate the html of forms -->

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>


<!-- <form action="/tasks" method="post">
  <%# hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">title: </label>
  <input type="text" title="task[title]" id="title">
  <label for="details">details: </label>
  <input type="text" title="task[details]" id="details">
  <input type="submit">
</form>
 -->

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<%= link_to "Back to all tasks", tasks_path %>